### ISSUE TITLE
Option to create service/layer without uploading data

### ISSUE THREAD

**Issue by cvanlith** [GeoCat/qgis-bridge-plugin#108]
In the geoserver definition tab under data you can now choose between: filebased, import handled by Bridge and import handled by Geoserver.
It would be nice to add a 4th option: use data location as is without uploading data.

Use this option if the data is already there, as the user created a layer in qgis directly from the PostGIS dataset.

This would be a great way to create services with styled layers for existing tables.

**Comment by jodygarnett** [comment]
I thought this was available via a database link option? As long as QGIS and GeoServer can see the same database there should be no need to upload the data at all ...

**Comment by pvgenuchten** [comment]
@jodygarnett the feature is available in Bridge for ArcMAP, idea of this issue is to port it to the QGIS editionn. There are some aspects to this issue:

- Bridge could be responsible for creating the datastore (db connection) on GeoServer side, or use one of the existing pg-datastores (copied from the default workspace)
- If bridge creates a datastore, it should should consider that geoserver may not have access to that database, and inform the user about that (by creating the store and see if succesfull)
- Supported database flavours could be PostGIS, Oracle, SQL-server, mysql, GPKG
- If user unchecks certain fields from publication, the geoserver layer can be set up as a sql layer using "select field,field,field from table" as a source.

**Comment by pvgenuchten** [comment]
Sorry again, I was not aware but seems this feature is actually available (for postgis only)

Make sure qgis and geoserver are able to connect to the same database
Then select this option in the server config in bridge
![image](https://user-images.githubusercontent.com/299829/81951862-fb19db00-9605-11ea-87d4-172fbd8b1cf2.png)
Bridge will use the qgis connection details to create a geoserver datastore to access the data

I just tested and works ok-ish, i was surpised to see a datastore being created for each layer published. Looking forward to hear feedback from community.
