### ISSUE TITLE
Server connection succeeds, publish fails

### ISSUE THREAD

**Issue by antonys** [GeoCat/qgis-bridge-plugin#125]
I'm using Bridge to create a connection to a GeoServer instance sitting in GeoNode, and can successfully make the server connection to GeoServer, but when I publish a layer I get a message 'Could not connect to Geoserver. Please check the server settings (including password)'. It's been suggested that the issue might be permissions or https (though it's an http site), so I'm wondering if there's something in the GeoServer config that needs to be changed. Has anyone else come across this, or has any suggestions on how to resolve? I'm using 4.02 of Bridge on QGIS 3.16, and GeoServer 2.17.

**Comment by GeoSander** [comment]
Hi @antonys, did you manage to publish successfully in the meantime? Did you also check if the GeoServer user you selected has sufficient permissions to publish stuff?
Since you are using GeoNode, I was also wondering what authentication type has been configured. Bridge can only deal with Basic authentication (for now), so something like OAuth(2) would not work yet, unfortunately.

**Comment by funny12138** [comment]
geoserver2.16及以上存在发布时无法连接的问题，2.15以及下没有问题，查看geoserver的升级日志，我觉得应该是geoserver的原因。

**Comment by funny12138** [comment]
geoserver2.16及以上存在发布时无法连接的问题，2.15以及下没有问题，查看geoserver的升级日志，我觉得应该是geoserver的原因。

**Comment by GeoSander** [comment]
> 这个插件在GeoServer版本适配上有些bug，geoserver.py文件的checkMinGeoserverVersion函数需要做些修改。

Thanks for reporting @funny12138. Google translates this as:

_This plug-in has some bugs in GeoServer version adaptation, and the checkMinGeoserverVersion function of the geoserver.py file needs to be modified._

Do you have any concrete suggestions for improvement?
We haven't encountered any bugs for regular GeoServer setups, Which bug(s) did you find and for what server setup do you use?

**Comment by funny12138** [comment]
@antonys 你使用的是Geoserver 2.17-SNAPSHOT吗？
if "SNAPSHOT" in ver:
    temp1, temp2 = ver.split('-')
    ver_major, ver_minor = temp1.split('.')
else:
    ver_major, er_minor, ver_patch = ver.split('.')

**Comment by GeoSander** [comment]
Yes @funny12138, if you're using a GeoServer nightly build or dev version (in this case a non-official release that ends in `-SNAPSHOT`), the code will indeed fail when doing `int(ver_minor)` on [this line](https://github.com/GeoCat/qgis-bridge-plugin/blob/master/geocatbridge/publish/geoserver.py#L902). However, since this happens in a try-except block, this should merely [log a warning](https://github.com/GeoCat/qgis-bridge-plugin/blob/master/geocatbridge/publish/geoserver.py#L911) and not raise an error, right?
Therefore, I don't think that this relates to the issue that @antonys reported. Did you have any problems connecting to GeoServer using Bridge because of this?
