### ISSUE TITLE
Error connecting to GeoServer under proxy

### ISSUE THREAD

**Issue by bogind** [GeoCat/qgis-bridge-plugin#142]
Trying to create a new GeoServer connection using latest (v4.1.3) with QGIS 3.16.8 OS windows 10.
I am behind a proxy but my GeoServer is running locally.
Trying to use the full computer name or "localhost" I am getting this error:

`Error: Could not connect to GeoServer: HTTPConnectionPool(host='proxyhost', port=proxyport): Max retries exceeded with url: http://m2132305-w10:8080/geoserver/rest/about/version (Caused by ResponseError('too many 504 error responses'))`

Trying to connect using 127.0.0.1 I am getting:

`Error: Could not connect to GeoServer: 403 Client Error: Forbidden for url: http://127.0.0.1:8080/geoserver/rest/about/version`

Resetting the proxy connections, or reopening QGIS does nothing.

**Comment by bogind** [comment]
Saw your use of `requests` and suspected that was the reason.

Can you help point me where should I look (in the plugin files) to start replacing `requests` with the` QgsNetworkAccessManager`?

I am already somewhat familiar with it and would like to help if my organization will be able to spare the man hours for this.

**Comment by GeoSander** [comment]
Replacing `requests` with the `QgsNetworkAccessManager` is not an easy task.
We either need all requests by the `QgsNetworkAccessManager` to be blocking (same behavior as the `requests` lib) OR we need to await the responses, which may mean that the whole async/await pattern will spread through the codebase like a weed.
The `QgsNetworkAccessManager` for the latest QGIS LTR (2.16), which is the minimum version that we wish to support, only provides a `blockingGet` and a `blockingPost` method, but we would also need a `blockingPut` at least, and preferably also a `blockingDelete`. If these methods would all exist, this will make our work a lot easier...

However, any help is greatly appreciated, so feel free to fork and experiment a little.
All outgoing catalog server model traffic (GeoServer and GeoNetwork mainly) is handled by [this wrapper function](https://github.com/GeoCat/qgis-bridge-plugin/blob/master/geocatbridge/servers/bases.py#L195). So that might be a good starting point for you.

**Comment by bogind** [comment]
Forgot about having to use `PUT` and `DELETE`, have you considered using the [qnetworkaccessmanager](https://doc.qt.io/qt-5/qnetworkaccessmanager.html) directly instead of `QgsNetworkAccessManager`?

**Comment by GeoSander** [comment]
Sure, but what's the benefit? I can do any kind of HTTP request with the `QgsNetworkAccessManager`, but it's all non-blocking, just like the `QNetworkAccessManager`. So then we still need to make blocking wrappers for those requests OR register event handlers for all requests in the server modules, which probably means a lot of refactoring.

**Comment by GeoSander** [comment]
Hi @bogind,

I was going through some issues and realized that I never got back to this one, even though a [workaround  is available](https://geocat.github.io/qgis-bridge-plugin/v4.2/server_configuration.html?highlight=proxy#proxies-certificates).

Replacing `requests` with the `QgsNetworkAccessManager` is still planned for the coming months though.

Closing this ticket now. Will report back when `requests` has been replaced.

Sander
