### ISSUE TITLE
Failed to create datastore

### ISSUE THREAD

**Issue by Jenusdy** [GeoCat/qgis-bridge-plugin#166]
**Describe the bug**
Failed to create datastore <filename> from <path>: string longer than 2147483647 bytes

**To Reproduce**
1. I try to publish service on Geoserver using my gpkg file 
2. The file size 11.8GB
3. See error
![Screenshot 2024-03-24 160002](https://github.com/GeoCat/qgis-bridge-plugin/assets/23545319/1a4b2014-11a0-4434-be6e-46ddb3ef05ba)

**Environment info (please complete the following information):**
 - OS: Windows
 - QGIS version: 3.28-7 / Firenze
 - Bridge version: v4.4
 - Python version: 3.10

**Comment by GeoSander** [comment]
Hi @Jenusdy,

I am sorry, but Bridge has not been designed for (GeoPackage) files of that size.
I assume that this happens when Bridge tries to zip up the GeoPackage before it pushes it to GeoServer.

Even if it was able to read that byte stream, the GeoServer REST API would still choke on it, as it will likely not accept incoming `POST` HTTP requests with a payload of that size.

Nevertheless, handling large datasets is something that we are considering, along with WebDAV support so you will also be able to successfully upload the file.

Sander
