### ISSUE TITLE
click behaviour layers publish panel not optimal

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#55]
The click behaviour on layers in publish panel, is not clear:

![image](https://user-images.githubusercontent.com/299829/72913543-94627000-3d3d-11ea-8d28-10e29142c300.png)

- When you click on the label, it (de) activates the checkbox
- When you click around the label it activates the layer

I would use the click on label to activate the layer, and only a click on checkbox to (de)activate the checkbox

Other option is to not show checkboxes here (only show the layers which are set visible in map TOC)

**Comment by GeoSander** [comment]
I have always been annoyed by this very peculiar behavior (it's a Qt thing) and I was never able to improve this in a way that turned out to be satisfactory.

However, the UI/UX of the upcoming Bridge 5.0 release will be quite different. The checkbox list widgets will no longer be used in that GUI, which basically auto-solves this issue.
